### ISSUE TITLE
install.py is unavailable

### ISSUE THREAD

**Issue by ShangLand** [Yonisen/WarThunder_Yellow_Mark_Rangefinder#8]
When I run miniMap.py show this:

  File "C:\Program Files\WarThunder_Mark\distance\miniMap.py", line 50, in <module>
    file = open('code/pid.txt', 'w')
PermissionError: [Errno 13] Permission denied: 'code/pid.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WarThunder_Mark\distance\miniMap.py", line 128, in <module>
    file = open('error.log', 'a')
PermissionError: [Errno 13] Permission denied: 'error.log'

**Comment by ShangLand** [comment]
This is just an error caused by running permissions. Do not attempt to run the file from the C drive.
